"""create drift_events table

Revision ID: 133d1490bda7
Revises: 
Create Date: 2026-05-26 16:20:02.464510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133d1490bda7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('drift_kind', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('intent', sa.JSON(), nullable=True),
    sa.Column('reality', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drift_events')
    # ### end Alembic commands ###
